export const actionTypes = {
  LOAD_TEST_SUITES: 'LOAD_TEST_SUITES',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  TOGGLE_TESTSUITE: 'TOGGLE_TESTSUITE'
};

export const visibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_SUCCESS_ONLY: 'SHOW_SUCCESS_ONLY',
  SHOW_FAILURE_ONLY: 'SHOW_FAILURE_ONLY',
  SHOW_SKIPPED_ONLY: 'SHOW_SKIPPED_ONLY'
};
